### ISSUE TITLE
feed update does not update favicon

### ISSUE THREAD

**Issue by vujevits** [felfele/felfele#208]
**Describe the bug**
Creating a feed, and later changing the favicon does not update the favicon.

**To Reproduce**
1. Create feed
2. Add profile image
3. Share post
4. Feed image is not added / updated

**Expected behavior**
An update to the profile picture should happen either when adding the image, or when uploading a  new post.

**Comment by agazso** [comment]
Also if you change your name, the name of the (by default associated) feed won't change.

**Comment by agazso** [comment]
I think there are multiple issues here. If you create a new identity and share a post, then:
- in the `RecentPostFeed`:
  - the `favicon` field is empty (this might be okay)
  - but the `url` property from the `authorImage` is also missing (only `width` and `height` is provided)
  - in the post itself there is an `author` property 
    - which also has an empty `faviconUri` field (this might be okay)
    - it has an `image` property with an `uri` property which is also empty
- in the `PostCommandLog`:
  - `author` is missing from the post

**Comment by agazso** [comment]
Here is an example output of a new identity with one post shared:

```
+ node build/dist/src/cli.js swarm feed 0xefc70d65efbadbda7379f7f834ca22cde5f7601c
Recent post feed {
    "name": "Space Cowboy",
    "url": "bzz-feed:/?user=0xefc70d65efbadbda7379f7f834ca22cde5f7601c",
    "feedUrl": "bzz-feed:/?user=0xefc70d65efbadbda7379f7f834ca22cde5f7601c",
    "favicon": "",
    "posts": [
        {
            "images": [
                {
                    "uri": "https://swarm.felfele.com/bzz-raw:/f67a1c636b2cef6b20135e0ec4d17a70090f536ff6d81a5262049b226a11c3eb/image.png",
                    "width": 4288,
                    "height": 2848
                }
            ],
            "text": "",
            "createdAt": 1552923386597,
            "link": "bzz://dfd5fcc6bc28c7503190ce6ec12dd2dfd2fc1abea75b8cbb01187ab85df733da",
            "author": {
                "name": "Space Cowboy",
                "uri": "bzz-feed:/?user=0xefc70d65efbadbda7379f7f834ca22cde5f7601c",
                "faviconUri": "",
                "image": {
                    "uri": ""
                }
            }
        }
    ],
    "authorImage": {
        "width": 4288,
        "height": 2848
    }
}
Posts:
{
    "protocolVersion": 1,
    "id": {
        "timestamp": 1,
        "source": ""
    },
    "parentId": {
        "timestamp": 0,
        "source": ""
    },
    "post": {
        "images": [
            {
                "uri": "bzz://f67a1c636b2cef6b20135e0ec4d17a70090f536ff6d81a5262049b226a11c3eb/image.png",
                "width": 4288,
                "height": 2848
            }
        ],
        "text": "",
        "createdAt": 1552923386597,
        "link": "bzz://dfd5fcc6bc28c7503190ce6ec12dd2dfd2fc1abea75b8cbb01187ab85df733da"
    },
    "type": "update",
    "epoch": {
        "time": 1552923412,
        "level": 25
    }
}

```

**Comment by agazso** [comment]
Also the post image `uri` in the `RecentPostFeed` is already a gateway url, it should be a plain bzz url.
