### ISSUE TITLE
Using opaque (or nominal) types proposal

### ISSUE THREAD

**Issue by agazso** [felfele/felfele#252]
Sometimes it would be good to define types that act like strings or numbers, but have additional type information so that they cannot be used incorrectly.

For example we can define separate opaque string types for URLs, Colors, Names or number types for Timestamps or Ids.

One implementation I found is this:
```typescript
type Opaque<T, N> = T & {__tag__?: N};

type OpaqueString<T> = Opaque<string, T>;
type PersonID = OpaqueString<'PersonID'>;
type UserID = OpaqueString<'User'>;

let p: PersonID = '';
const u: UserID = '';
p = u; // Error!
```

**Comment by vujevits** [comment]
I like it! But for Colors (anything available at compile time) a literal type should be enough, right?

**Comment by agazso** [comment]
So these are literal types, but at compile time the compiler can check if it's correct.

For example, using the definitions above, we can do the following things:
```typescript
type Color = OpaqueString<'Color'>;
const changeColor = (color: Color) => {
    // whatever
}
const BLACK = '#000000' as Color;

changeColor('#ffffff') // OK
changeColor(BLACK) // OK
changeColor(u) // Error! `u` is UserID
```

This can be helpful when there are functions with multiple string arguments (e.g. `createIcon(path: string, color: string)` => `createIcon(path: Path, color: Color)`) or if we want to differentiate between different types that are represented as strings (e.g. `SwarmLink` or `LocalLink`).

This article writes about more and it even differentiates between two techniques called Flavoring and Branding, where Branding is stronger and can be even used for run-time checks:
https://spin.atomicobject.com/2018/01/15/typescript-flexible-nominal-typing/

**Comment by vujevits** [comment]
What I meant by being available at compile time is the possible values you want to use as Colors, because then simply doing 
```typescript
type Color = '#000000' | '#ffffff'
```
is enough.
But I totally agree with the need of opaque types, I'm not sure about the flavor. Both have their valid use-cases.
