### ISSUE TITLE
'All feeds' are displayed in one column

### ISSUE THREAD

**Issue by agazso** [felfele/felfele#259]
'All feeds' are displayed in one column on android. When you open the screen, for a moment it is shown in two columns, but then it stays in one column.

**To Reproduce**
1. Go to 'All feeds'
2. See error

**Expected behavior**
All feeds should be displayed in two columns. 

**Screenshots**
<img width="644" alt="Screen Shot 2019-03-27 at 11 35 31" src="https://user-images.githubusercontent.com/230163/55069778-1b46ad80-5085-11e9-9114-af989ea87b3f.png">

**Smartphone (please complete the following information):**
I tried it in Genymotion 2.9
 - Device: Google Nexus 5X
 - OS: Android 7.1.0

**Additional context**

**Comment by vujevits** [comment]
I can only reproduce it on the simulator, but not on a real device. @agazso can you verify?

**Comment by agazso** [comment]
I could reproduce on real device too

**Comment by agazso** [comment]
I managed to reproduce it on the iPhone 5s in the simulator too
