### ISSUE TITLE
No indication of loading in the feed discovery.

### ISSUE THREAD

**Issue by giurim** [felfele/felfele#263]
**Describe the bug**
When I opened the philosophy subcategory it showed one item, but later it loaded a second one. 

**To Reproduce**
1. Go to 'All feeds'
2. Click on 'Expolore public feeds'
3. Choose 'humanities and social sciences'
4. Choose 'philosophy'

**Expected behavior**
An indication that content is still loading would be great (a loading indicator instead of the refresh sign)

**Screenshots**
![54435801_2131161973636395_4632488452007395328_n](https://user-images.githubusercontent.com/15023637/55092855-9f178e80-50b3-11e9-804c-1330a5826819.png)
![55478011_2216827958406007_1896373029215141888_n](https://user-images.githubusercontent.com/15023637/55092863-a2ab1580-50b3-11e9-8137-c562297bd4aa.png)

**Comment by vujevits** [comment]
what device and os version have you used?

**Comment by giurim** [comment]
Android 8.1.0
Nexus 5X

**Comment by vujevits** [comment]
I've seen the same issue happening on my phone, but in the gmail client and another app as well, but not in our's.

**Comment by vujevits** [comment]
We will optimize networking by including in the news.json the url to the icons of the feeds, so they don't have to be looked up.

**Comment by agazso** [comment]
Fixed by #334
