### ISSUE TITLE
bug report email only works with default email app on iOS

### ISSUE THREAD

**Issue by vujevits** [felfele/felfele#274]
**Describe the bug**
If the Mail app is removed from the iPhone, it will only offer to download it from the App Store.

**To Reproduce**
1. navigate to report a bug
2. press send
3. popup asks you to download the mail app

**Expected behavior**
An email client should open

**Comment by agazso** [comment]
I found this

https://github.com/leanmotherfuckers/react-native-email-link

**Comment by vujevits** [comment]
I've seen it as well, it's a bit different from what we need but the code is very short so I'll modify it to our needs.
