### ISSUE TITLE
Name/profile picture change during onboarding

### ISSUE THREAD

**Issue by agazso** [felfele/felfele#317]
Most people does not change the default name and profile picture. We have a hypothesis that it's because at that point in the onboarding they are not sure how would they use the app, what it is good for, who they will share it etc. This is only one hypothesis and there may be other reasons.

Ideas to mitigate this:
- Use generated profile pictures (like Slack, Github etc.)
- Use randomized names. Some people told me that they actually like being 'Space Cowboy' :)

Other thoughts, hypothesis and ideas are welcome in this discussion thread!

**Comment by vujevits** [comment]
I agree with both ideas :-) 

Especially early on people don't get a sense of the network, they are not aware of possible customs etc., like some users asked if they have to input their real name. Providing generated names can fasten up the onboarding, and also suggesting that using a real name is not required.
Same stands for the profile picture.
