### ISSUE TITLE
Sharing who I follow for easier first time experience

### ISSUE THREAD

**Issue by balazsbajorics** [felfele/felfele#320]
**Is your feature request related to a problem? Please describe.**
To make a new user's onboarding easier, they should be able to find friends and make connections to them, so they are not alone in the application.

**Describe the solution you'd like**
I would like to be able to show a QR code, that lets my friend see the list of accounts that I follow. This would mean that they can kickstart using Felfele with a handful of accounts already followed, not just mine.

**Describe alternatives you've considered**
I think this is a good middle ground between the current solution (following friends one-by-one) and an aggressive facebook- or twitter-like "steal your contact info" one. It still requires one friend to "initiate" the user, but I think that adds a bit of personal touch to the experience.

**Additional context**
Don't do this: https://www.businessinsider.com/facebook-uploaded-1-5-million-users-email-contacts-without-permission-2019-4

**Comment by vujevits** [comment]
We could also display a QR code for this based on different aggregations of a user's feeds.
At the moment it could be: favorites
