### ISSUE TITLE
reshared channel name with ellipsis glitch on android

### ISSUE THREAD

**Issue by vujevits** [felfele/felfele#374]
**Describe the bug**
The right side of the text is off the screen.

**To Reproduce**
1. Share post from long-named-channel

**Expected behavior**
The text should have a padding on the right

**Screenshots**
![Screenshot_20190516-110748](https://user-images.githubusercontent.com/2270661/57841821-9302a000-77cb-11e9-8dcd-2ad29496aef3.png)

**Smartphone (please complete the following information):**
 - Device: LG Nexus
 - OS: Android

**Comment by agazso** [comment]
This was supposed to be fixed in this PR: 
https://github.com/felfele/felfele/pull/373

**Comment by vujevits** [comment]
You are right, I mixed up the 2 devices with different app versions
