### ISSUE TITLE
Refreshing private channels takes long time

### ISSUE THREAD

**Issue by agazso** [felfele/felfele#524]
**Describe the bug**
Refreshing private channels takes long time. For example with 6 contacts it can take 30 seconds.

The problem is that fetching the updates can take 5 seconds and they are done sequentially. One possible fix could be to parallelise the requests.

**Comment by vujevits** [comment]
about the parallelisation: the default maximum http connection per host is 4 on iOS, but it can be changed
https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc
