### ISSUE TITLE
Commenced worklog is not displayed

### ISSUE THREAD

**Issue by vujevits** [felfele/felfele#576]
**Describe the bug**
Commenced worklog is not displayed.

**To Reproduce**
1. Go to My work log or jobsite specific worklog for user.
2. There are no logs present.

**Expected behavior**
Worklogs for today should be listed.

**Screenshots**
I'm there: 
<img width="544" alt="Screenshot 2020-01-20 at 16 57 54" src="https://user-images.githubusercontent.com/2270661/72740503-1586ff00-3ba6-11ea-8fb7-818446b6cd21.png">

Jobsite and user specific worklog:

<img width="544" alt="Screenshot 2020-01-20 at 16 58 01" src="https://user-images.githubusercontent.com/2270661/72740536-259ede80-3ba6-11ea-8b94-2efb648c6c29.png">

My work log:
<img width="544" alt="Screenshot 2020-01-20 at 16 58 11" src="https://user-images.githubusercontent.com/2270661/72740551-30597380-3ba6-11ea-8e14-221f636ea2eb.png">

**Additional context**
Data is not there in the checkins DB either

**Comment by agazso** [comment]
I think you opened this issue in the wrong project :)

**Comment by vujevits** [comment]
damn... Please delete this issue, here is how:
https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/allowing-people-to-delete-issues-in-your-organization
