### ISSUE TITLE
Multiple photos / telling a story

### ISSUE THREAD

**Issue by agazso** [felfele/felfele#67]
Ideas:
- One post with multiple photos
- Create a temporary feed for a story, put posts in them

**Comment by david-gauquelin** [comment]
I just saw #19 and I think the 2nd point above is similar

**Comment by vujevits** [comment]
solved by #179

**Comment by agazso** [comment]
We can iterate on the carousel to make the interaction better:
- Use letterboxing to fit images with different format, the first image determines the aspect ratio
- Tapping on the carousel stops the images, and then they can be swiped manually
- If there is no manual swipe for X seconds, the carousel continues automatically
- When the carousel is stopped we display the dots, otherwise they are hidden
- The carousel always goes from left to right

https://app.zeplin.io/project/5c5332113af383308745c1b2/screen/5c9cfdf3c2d2d2052d6b4074
